
-- CA, UI and UU. Leader Trait dealt with separately. Add granted traits
INSERT OR REPLACE INTO CivilizationTraits (TraitType, CivilizationType) VALUES	('TRAIT_CIVILIZATION_ADJACENT_DISTRICTS', 'CIVILIZATION_IMP_JAPABULLARABCREE');
INSERT OR REPLACE INTO CivilizationTraits (TraitType, CivilizationType) VALUES	('TRAIT_CIVILIZATION_BUILDING_MADRASA', 'CIVILIZATION_IMP_JAPABULLARABCREE');
INSERT OR REPLACE INTO CivilizationTraits (TraitType, CivilizationType) VALUES	('TRAIT_CIVILIZATION_UNIT_CREE_OKIHTCITAW', 'CIVILIZATION_IMP_JAPABULLARABCREE');
